# -*- coding: utf-8 -*-
"""News_finder_new.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fASI6GVkNH9SzJLroBvEaPbQOs4NFn-e
"""

import streamlit as st
import requests
from transformers import pipeline
from bs4 import BeautifulSoup

# Step 1: Fetch Related Articles
def fetch_related_articles(query, api_key, num_articles=5):
    url = f"https://newsapi.org/v2/everything?q={query}&sortBy=relevance&pageSize={num_articles}&apiKey={api_key}"
    response = requests.get(url)
    articles = response.json().get("articles", [])

    results = []
    for article in articles:
        title = article.get("title", "No title")
        content = article.get("content", "No content")
        article_url = article.get("url", "No URL available")

        if not content and article_url != "No URL available":
            content = fetch_full_article(article_url)

        results.append({"title": title, "content": content, "url": article_url})

    return results

def fetch_full_article(url):
    try:
        response = requests.get(url, timeout=10)
        soup = BeautifulSoup(response.content, "html.parser")
        paragraphs = soup.find_all("p")
        return " ".join([para.get_text() for para in paragraphs])
    except Exception as e:
        print(f"Error fetching article from {url}: {e}")
        return ""

# Step 2: Summarize Articles
def summarize_articles(articles, max_length=100, min_length=50):
    summarizer = pipeline("summarization", model="facebook/bart-large-cnn")

    summarized_articles = []
    for article in articles:
        content = article["content"]
        if len(content.split()) > 20:
            summary = summarizer(content, max_length=max_length, min_length=min_length, do_sample=False)
            summarized_articles.append({
                "title": article["title"],
                "summary": summary[0]["summary_text"],
                "url": article["url"]
            })
        else:
            summarized_articles.append({
                "title": article["title"],
                "summary": "Content too short to summarize.",
                "url": article["url"]
            })

    return summarized_articles

# Streamlit App
def main():
    st.title("News Summarizer App")
    st.write("Fetch and summarize news articles with ease!")

    # User inputs
    topic = st.text_input("Enter the topic you want to search for:", "Artificial Intelligence")
    num_articles = st.slider("Number of articles to fetch:", min_value=1, max_value=10, value=5)
    api_key = st.text_input("Enter your NewsAPI key:", type="password")

    if st.button("Fetch and Summarize Articles"):
        if not api_key:
            st.error("Please provide your NewsAPI key.")
            return

        st.write(f"Fetching articles about **{topic}**...")
        articles = fetch_related_articles(topic, api_key, num_articles)
        st.write("Summarizing articles...")
        summaries = summarize_articles(articles)

        # Display results
        for idx, summary in enumerate(summaries):
            st.subheader(f"Article {idx + 1}: {summary['title']}")
            st.write(summary['summary'])
            st.markdown(f"[Read more]({summary['url']})")

if __name__ == "__main__":
    main()